---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: metric
  namespace: dev
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metric
  template:
    metadata:
      labels:
        app: metric
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: metric
        image: quay.io/brice/metrics-demo@sha256:86126143b10728b621c08878da54f925813cb5fb89868572d2e960af3c7e7ff5
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: metric
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: metric
